const CACHE_NAME='papas-pos-v24';
const FILES=['./','./index.html','./styles.css','./app.js','./app-update.js','./excel-seed.js','./manifest.webmanifest','./icon.svg'];
const APP_FIX=`(()=>{
const originalPut=window.put;
window.inputDateToIso=function inputDateToIso(value){if(!value)return new Date().toISOString();const parts=value.split('-').map(Number);const year=parts[0];const month=parts[1];const day=parts[2];const now=new Date();return new Date(year,month-1,day,now.getHours(),now.getMinutes(),now.getSeconds(),now.getMilliseconds()).toISOString();};
window.put=function put(storeName,value){if(['sales','purchases','payments'].includes(storeName)&&value&&!value.createdAt)value.createdAt=new Date().toISOString();return originalPut(storeName,value);};
function cleanSafariText(){try{const backupBtn=document.querySelector('#backupBtn');if(backupBtn){backupBtn.textContent='Backup';backupBtn.classList.add('text-icon-button');backupBtn.setAttribute('title','Respaldar datos');}const backupText=document.querySelector('#backupText');if(backupText)backupText.setAttribute('placeholder','El respaldo aparecera aqui.');const pinInput=document.querySelector('#pinInput');if(pinInput)pinInput.setAttribute('placeholder','Clave');const form=document.querySelector('#varietyForm');if(form){form.classList.remove('hidden-control');const title=form.querySelector('h2');if(title)title.textContent='Nuevo producto';const labels=form.querySelectorAll('label');if(labels[0]&&labels[0].firstChild)labels[0].firstChild.nodeValue='Nombre del producto ';if(labels[1]&&labels[1].firstChild)labels[1].firstChild.nodeValue='Precio sugerido por saco ';const button=form.querySelector('button[type="submit"]');if(button)button.textContent='Guardar producto';}}catch(error){}}
function addCompatStyles(){if(document.querySelector('#papasCompatStyles'))return;const style=document.createElement('style');style.id='papasCompatStyles';style.textContent='.text-icon-button{width:auto;min-width:44px;padding:0 12px;font-size:.72rem;letter-spacing:.02em}.item-actions{display:grid;justify-items:end;gap:6px}.product-edit-dialog label{display:grid;gap:6px;margin-bottom:12px}.product-edit-dialog input{width:100%;box-sizing:border-box}';document.head.appendChild(style);}
function openAnyDialog(dialog){if(!dialog)return;if(typeof dialog.showModal==='function')dialog.showModal();else dialog.setAttribute('open','');}
function closeAnyDialog(dialog){if(!dialog)return;if(typeof dialog.close==='function')dialog.close();else dialog.removeAttribute('open');}
function ensureProductDialog(){if(document.querySelector('#productEditDialog'))return;const dialog=document.createElement('dialog');dialog.id='productEditDialog';dialog.className='pin-dialog product-edit-dialog';dialog.innerHTML='<form id="productEditForm" method="dialog" class="pin-card"><h2>Modificar producto</h2><input type="hidden" id="editProductId"><label>Nombre<input id="editProductName" type="text" autocomplete="off" required></label><label>Precio sugerido por saco<input id="editProductPrice" type="number" inputmode="numeric" min="1" required></label><div class="dialog-actions"><button class="secondary" type="button" id="cancelProductEditBtn">Cancelar</button><button type="submit">Guardar</button></div></form>';document.body.appendChild(dialog);document.querySelector('#cancelProductEditBtn').addEventListener('click',function(){closeAnyDialog(dialog);});document.querySelector('#productEditForm').addEventListener('submit',saveProductEdit);}
function safeEscape(value){if(typeof escapeHtml==='function')return escapeHtml(value);return String(value||'').replace(/[&<>"']/g,function(char){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char];});}
function openProductEdit(id){ensureProductDialog();const product=state.varieties.find(function(row){return row.id===id;});if(!product){showToast('Producto no encontrado');return;}document.querySelector('#editProductId').value=product.id;document.querySelector('#editProductName').value=product.name||'';document.querySelector('#editProductPrice').value=product.defaultPrice||state.settings.defaultPrice||0;openAnyDialog(document.querySelector('#productEditDialog'));setTimeout(function(){document.querySelector('#editProductName').focus();},80);}
async function saveProductEdit(event){event.preventDefault();const id=document.querySelector('#editProductId').value;const name=document.querySelector('#editProductName').value.trim();const defaultPrice=Number(document.querySelector('#editProductPrice').value)||0;const product=state.varieties.find(function(row){return row.id===id;});if(!product){showToast('Producto no encontrado');return;}if(!name){showToast('Ingresa el nombre');return;}if(defaultPrice<=0){showToast('Ingresa el precio');return;}const duplicated=state.varieties.some(function(row){return row.id!==id&&String(row.name).toLowerCase()===name.toLowerCase();});if(duplicated){showToast('Ese producto ya existe');return;}const updated=Object.assign({},product,{name:name,defaultPrice:defaultPrice,updatedAt:new Date().toISOString()});await put('varieties',updated);for(const sale of state.sales.filter(function(row){return (row.varietyId||DEFAULT_VARIETY_ID)===id;})){await put('sales',Object.assign({},sale,{varietyName:name,updatedAt:new Date().toISOString()}));}for(const purchase of state.purchases.filter(function(row){return (row.varietyId||DEFAULT_VARIETY_ID)===id;})){await put('purchases',Object.assign({},purchase,{varietyName:name,updatedAt:new Date().toISOString()}));}closeAnyDialog(document.querySelector('#productEditDialog'));await refresh();showToast('Producto modificado');}
function installInventoryEditor(){try{if(typeof state==='undefined'||typeof varietyStats!=='function'||typeof renderInventory!=='function')return;ensureProductDialog();renderInventory=function renderInventory(){const list=document.querySelector('#inventoryList');if(!list)return;list.innerHTML=state.varieties.length?state.varieties.map(function(variety){const stats=varietyStats(variety.id);return '<div class="list-item"><div class="item-main"><strong>'+safeEscape(variety.name)+'</strong><span class="item-meta">Comprados '+sacks(stats.purchased)+' - Vendidos '+sacks(stats.sold)+' - Costo prom. '+money(stats.avgCost)+'/saco - Sugerido '+money(stats.suggestedPrice)+'/saco</span></div><div class="item-actions"><span class="amount '+(stats.stock<=0?'debt':'positive')+'">'+sacks(stats.stock)+'</span><button class="edit-mini" type="button" data-edit-product-id="'+safeEscape(variety.id)+'">Modificar</button></div></div>';}).join(''):'<div class="empty">Agrega tu primer producto.</div>';};const list=document.querySelector('#inventoryList');if(list&&!list.dataset.productEditBound){list.dataset.productEditBound='1';list.addEventListener('click',function(event){const button=event.target.closest('[data-edit-product-id]');if(button)openProductEdit(button.dataset.editProductId);});}renderInventory();}catch(error){}}
function installPapasFixes(){cleanSafariText();addCompatStyles();installInventoryEditor();}
if('serviceWorker'in navigator){let reloading=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(reloading)return;reloading=true;window.location.reload();});navigator.serviceWorker.getRegistration().then((registration)=>{if(!registration)return;const activateWaiting=()=>{if(registration.waiting)registration.waiting.postMessage({type:'SKIP_WAITING'});};registration.addEventListener('updatefound',()=>{const worker=registration.installing;if(!worker)return;worker.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller)activateWaiting();});});registration.update().then(activateWaiting).catch(()=>{});});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',installPapasFixes);else installPapasFixes();setTimeout(installPapasFixes,250);setTimeout(installPapasFixes,1000);
})();`;
self.addEventListener('install',(event)=>{self.skipWaiting();event.waitUntil(caches.open(CACHE_NAME).then((cache)=>cache.addAll(FILES)));});
self.addEventListener('activate',(event)=>{event.waitUntil(caches.keys().then((keys)=>Promise.all(keys.filter((key)=>key!==CACHE_NAME).map((key)=>caches.delete(key)))).then(()=>self.clients.claim()));});
self.addEventListener('message',(event)=>{if(event.data?.type==='SKIP_WAITING')self.skipWaiting();});
self.addEventListener('fetch',(event)=>{if(event.request.method!=='GET')return;const url=new URL(event.request.url);if(url.pathname.endsWith('/app.js')){event.respondWith(caches.match(event.request).then((cached)=>cached||fetch(event.request)).then((response)=>response.text()).then((text)=>new Response(`${text}\n${APP_FIX}`,{headers:{'Content-Type':'application/javascript; charset=utf-8'}})));return;}event.respondWith(caches.match(event.request).then((cached)=>cached||fetch(event.request)));});